---
- name: OpenSearch Installation
  ansible.builtin.include_tasks: install.yml
  tags: [install, opensearch_install]

- name: OpenSearch Certificates
  ansible.builtin.include_tasks: certificates.yml
  tags: [install, opensearch_install, opensearch_certs]

- name: OpenSearch Rollback
  ansible.builtin.include_tasks: rollback.yml
  tags: [rollback, opensearch_rollback]
