---
opensearch_version: 3.4.0
opensearch_download_url: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version }}/opensearch-{{ opensearch_version }}-linux-x64.tar.gz"
opensearch_install_dir: /data/opensearch
opensearch_user: opensearch
opensearch_group: opensearch
opensearch_network_host: 0.0.0.0
opensearch_discovery_type: single-node
opensearch_security_enabled: true
opensearch_heap_size: "512m"
