---
opensearch_version: 3.4.0
opensearch_download_url: "https://artifacts.opensearch.org/releases/bundle/opensearch/{{ opensearch_version }}/opensearch-{{ opensearch_version }}-linux-x64.tar.gz"
opensearch_install_dir: /data/opensearch
opensearch_user: opensearch
opensearch_group: opensearch
opensearch_network_host: 0.0.0.0
opensearch_discovery_type: single-node
opensearch_security_enabled: true
opensearch_heap_size: "512m"

# Certificate configuration
opensearch_certs_local_dir: "{{ playbook_dir }}/certs"
opensearch_certs_root_subj: "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=ROOT"
opensearch_certs_admin_subj: "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=A"
opensearch_certs_node_subj: "/C=CA/ST=ONTARIO/L=TORONTO/O=ORG/OU=UNIT/CN=node1.dns.a-record"
opensearch_certs_node_dns: "node1.dns.a-record"
opensearch_certs_days: 730
